# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Disabled'), (1, 'Enabled')], default=1)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='photos')),
                ('cameraModel', models.CharField(max_length=255)),
                ('cameraLens', models.CharField(max_length=255)),
                ('focalLength', models.CharField(blank=True, max_length=255)),
                ('aperature', models.CharField(blank=True, max_length=255)),
                ('exposureTime', models.CharField(blank=True, max_length=255)),
                ('iso', models.CharField(blank=True, max_length=255)),
                ('share_facebook', models.BooleanField(default=False)),
                ('share_twitter', models.BooleanField(default=False)),
                ('share_googleplus', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_updated_datetime', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageCategory', to='photos.category')),
            ],
            options={
                'ordering': ['-created_datetime'],
            },
        ),
    ]
