# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-09 15:20
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='', upload_to='category'),
            preserve_default=False,
        ),
    ]
